# Generated by Django 5.0.2 on 2024-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="default-slug-value", max_length=250, unique=True
            ),
            preserve_default=False,
        ),
    ]
